### ISSUE TITLE
Change of address

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/website#15]
I guess we need to change the address and some details about going to the space.

The new address would be something like...
```
57 North Hackspace, care of Aberdeen Action On Disability
Units G&H
Kettock Lodge
2 Campus Two
Balgownie Dr
Bridge of Don
Aberdeen,
AB22 8GU
```
...does that sound ok?

**Comment by AndyGaskell** [comment]
As a one-liner, that'd be...
`Units G&H, Kettock Lodge, 2 Campus Two, Balgownie Dr, Bridge of Don, Aberdeen, AB22 8GU`

**Comment by Nordln** [comment]
I'll check with building rep and confirm asap.  Cheers, Ed.

---------- Forwarded message ---------

**Comment by AndyGaskell** [comment]
Happy to make the changes :)

**Comment by AndyGaskell** [comment]
Thanks @Nordln no rush I guess, as we're technically still in the old place too.

**Comment by AndyGaskell** [comment]
Think it's just 3 files that need to be updated...

https://github.com/hackerdeen/website/blob/master/contact.php
![Screenshot_2019-09-30 Contact » 57North Hacklab](https://user-images.githubusercontent.com/91541/65878353-ce21fc00-e385-11e9-94bb-2223ed17acf8.png)

https://github.com/hackerdeen/website/blob/master/about.php
![Screenshot_2019-09-30 About » 57North Hacklab](https://user-images.githubusercontent.com/91541/65878354-ce21fc00-e385-11e9-8cae-8056b50e8fde.png)

https://github.com/hackerdeen/website/blob/master/index.php
![Screenshot_2019-09-30 57North Hacklab](https://user-images.githubusercontent.com/91541/65878356-ce21fc00-e385-11e9-81e1-cf9d594db327.png)

**Comment by AndyGaskell** [comment]
@Midder-57N also made a tweak for the address, those changes are un-modified.

Everything is merged and ready to go, pending and ok from AAD, via @Nordln

**Comment by AndyGaskell** [comment]
Feedback from AAD, via Ed...

`Campus 2.
2, Balgownie Drive

Not 2 Campus Two`

**Comment by AndyGaskell** [comment]
fixed a wee while ago
