### ISSUE TITLE
Update board of directors

### ISSUE THREAD

**Issue by irl** [hackerdeen/website#29]
It doesn't currently reflect reality

**Comment by AndyGaskell** [comment]
It looks like this now at https://www.57north.org.uk/about
![Screenshot 2023-04-25 21 22 39](https://user-images.githubusercontent.com/91541/234394962-99399447-6f94-4dc2-82b6-1b8021ef95df.png)

**Comment by AndyGaskell** [comment]
We need to add Wouter

**Comment by AndyGaskell** [comment]
![Screenshot 2023-05-09 at 22-06-57 About » 57North Hacklab](https://github.com/hackerdeen/website/assets/91541/33e34b9f-cc38-4cc4-9572-60ce066426a7)
