### ISSUE TITLE
Add Facebook link

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/website#34]
We could add this back into the header I guess.  Just next to the twitter one.

**Comment by AndyGaskell** [comment]
This would rewind some changes in...
https://github.com/hackerdeen/website/commit/5cfea8bd7f33724650e3d2fea5690666a0c7f511
...but I think it's ok

**Comment by ormiret** [comment]
I vaguely remember this was removed after some folks tried to get in touch with us on facebook and got no response as none of us were paying attention to facebook. Do we have someone(s) who'll be paying attention to facebook now if we're pointing people to it again?

**Comment by AndyGaskell** [comment]
Hi @ormiret 

Yea, I should have mentioned that.  I've been making sure to check in on Facebook and Twitter at least once a week.  I try and do a post every Tuesday, mentioning Open Eve.  

Twitter is easy to spot messages, but Facebook's UI is horrible, so messages are not always obvious, so I created an automation on Facebook that should help any we miss.  It's not ideal, but hopefully semi-useful, it looks like this...
![facebook_automation](https://github.com/hackerdeen/website/assets/91541/caa10b11-2f20-41e0-9888-a944e8b59db1)
