### ISSUE TITLE
Update the "Events" page

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/website#36]
![Screenshot 2023-04-25 21 19 47](https://user-images.githubusercontent.com/91541/234393990-9fcfc539-58c2-4136-868d-0914a93fa8e2.png)

**Comment by AndyGaskell** [comment]
Since we're not really doing events at the moment, maybe we could remove the "Events" menu item and set a forward to the new Open Evenings page.

 Add a new "Open Evenings" page #35

**Comment by Hibby** [comment]
Maybe 'visit us' or 'what's on' or something?

**Comment by AndyGaskell** [comment]
Yea, it'd be nice if there were actual events.  The current "Events" page's content is really all just about Open Evenings.  I think the 'visit us' or 'what's on' sort of user stories should be covered by the new Open Evenings page, see #35
