### ISSUE TITLE
Add an "Our Space" page

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/website#38]
It might be good to have a page that describes the space.

This would be mostly photos I think.

**Comment by AndyGaskell** [comment]
The new page currently looks like this...
![our_space_page_01](https://github.com/hackerdeen/website/assets/91541/6210c27d-068a-4cb3-9048-6e6a6a770d05)

**Comment by Hibby** [comment]
I estimate us as being at 300m2.  Do we link the howtos from the wiki? 
https://wiki.57north.org.uk/doku.php?id=space:howto
