### ISSUE TITLE
Add a "Membership" page

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/website#41]
Provide details of membership, costs, benefits, process etc.

Also provide info on remote membership, as per...
[AGM 2023, Set fee level for remote membership](https://github.com/hackerdeen/meetings/blob/master/2023/2023-04-04_AGM_Minutes.md#11-set-fee-level-for-remote-membership)

This will improve transparency and might even help people decide to join.

See also https://wiki.57north.org.uk/doku.php?id=admin:membership_application_process

**Comment by AndyGaskell** [comment]
we could include...
- How guests are allowed with members
- Pointers for members hosting events
- General expectations of members

**Comment by AndyGaskell** [comment]
So far it's looking like this...
![issue41_membership_page_01](https://github.com/hackerdeen/website/assets/91541/5e8305f7-1679-4316-83ed-9073161ea973)

**Comment by Hibby** [comment]
Yeah, looks good. Strong agree on the diversity page being a webpage, it protects us from malicious edits. I'll draft a form this afternoon using a combination of MS Office and Adobe :)

**Comment by Hibby** [comment]
A first pass! 

[57North Membership form.pdf](https://github.com/hackerdeen/website/files/11478697/57North.Membership.form.pdf)

**Comment by Hibby** [comment]
[57North Membership form PDF Form 2.pdf](https://github.com/hackerdeen/website/files/11478999/57North.Membership.form.PDF.Form.2.pdf)

Updated revision, I like this one more!

**Comment by AndyGaskell** [comment]
That form looks great, nice one :) 

I created a new "Statement on Equality and Diversity" page #45

**Comment by adventureloop** [comment]
Form probably shouldn't have the bank details - our process should be to respond with the details and the reference for the new member to use.

**Comment by AndyGaskell** [comment]
Yea, I'm never sure about publishing bank details.  I put them on all my invoices, but they're not really published to the world.
* Page: https://www.57north.org.uk/membership
* Form: https://www.57north.org.uk/57North%20Membership%20Form.pdf

**Comment by Hibby** [comment]
> Form probably shouldn't have the bank details - our process should be to respond with the details and the reference for the new member to use.

Fixed in commit c9fab17
