### ISSUE TITLE
Fix the converged logo, broken image link

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/website#43]
On the Home screen and the sponsors screen, the converged logo is a broken image link.  In both instances it points to https://57north.org.uk/w/images/f/f9/Converged-logo.jpg

https://www.57north.org.uk/
![Screenshot 2023-05-10 at 09-04-34 57North Hacklab](https://github.com/hackerdeen/website/assets/91541/8da236b7-7fc1-4224-ade0-afdd27c90684)

https://www.57north.org.uk/sponsors
![Screenshot 2023-05-10 at 09-04-06 Sponsors » 57North Hacklab](https://github.com/hackerdeen/website/assets/91541/81322a1f-7137-4325-8309-f92130b10c45)

**Comment by Hibby** [comment]
image is gone as converged don't give us any service - our current ISP is aaisp.

**Comment by Hibby** [comment]
I think they didn't ask explicitly but I'm game yeah

**Comment by AndyGaskell** [comment]
Cool, done :)

**Comment by AndyGaskell** [comment]
Updated sponsors bit on the home page...
![issue43_sponsors_home](https://github.com/hackerdeen/website/assets/91541/e3d794b0-4d01-4761-a43a-1898cb9aba40)

Updated sponsors page...
![issue43_sponsors_page](https://github.com/hackerdeen/website/assets/91541/0a865cb5-379b-4a9c-bbec-5aee2f7484c9)
